
const voiceList = [
    { name: "愛してるよ", file: "voice/aisiteruyo.wav" },
    { name: "ありがとね1", file: "voice/arigatone.wav" },
    { name: "ありがとね2", file: "voice/arigatone2.wav" },
    { name: "ありがとね3", file: "voice/arigatone3.wav" },
    { name: "chu!料理できてごめん", file: "voice/churyouridekitegomen.wav" },
    { name: "電話が来たよ！", file: "voice/denwagakitayo.wav" },
    { name: "どこいった", file: "voice/dokoitta.wav" },
    { name: "えへえへ", file: "voice/eheehe.wav" },
    { name: "元気だして", file: "voice/genkidasite.wav" },
    { name: "はわわっんん", file: "voice/hawawann.wav" },
    { name: "はわわわわわわ", file: "voice/hawawawawa.wav" },
    { name: "へっへっへっへっへっへ", file: "voice/hehhehhehhehhehhe.wav" },
    { name: "ひき肉です", file: "voice/hikinikudesu.wav" },
    { name: "ふぇっ", file: "voice/hue.wav" },
    { name: "ふぇっはっああ……", file: "voice/huehahhaa.wav" },
    { name: "触れるんじゃない", file: "voice/hurerunjanai.wav" },
    { name: "勢いつかないです", file: "voice/ikioitukanaidesu.wav" },
    { name: "いらっしゃいませ", file: "voice/irasshaimase.wav" },
    { name: "いらっしゃいません", file: "voice/irasshaimasenn.wav" },
    { name: "（作者）", file: "voice/kakkosakusha.wav" },
    { name: "勘弁してくれ", file: "voice/kanbensitekure.wav" },
    { name: "彼女がいない？なら私を推しましょう！", file: "voice/kanojogainai.wav" },
    { name: "かつぜちゅ……かつぜちゅー……", file: "voice/katuzetyu.wav" },
    { name: "来てくれてありがっとう助かるよ", file: "voice/kitekuretearigatou.wav" },
    { name: "きつねたぬきてんぷらつきみ", file: "voice/kittunetanukitenpuratukimi.wav" },
    { name: "こんばんは", file: "voice/konbanha.wav" },
    { name: "このアーカイブは消します", file: "voice/konoakaibuhakesimasu.wav" },
    { name: "まったく", file: "voice/mattaku.wav" },
    { name: "無理だって", file: "voice/muridatte.wav" },
    { name: "無理", file: "voice/murisinaidene.wav" }, // ID 30-31付近
    { name: "無理しないでね", file: "voice/murisinaidene.wav" },
    { name: "流しそうめん", file: "voice/nagassisoumen.wav" },
    { name: "寝ないの？", file: "voice/nenaino.wav" },
    { name: "寝ちゃえ", file: "voice/netyae.wav" },
    { name: "お風呂も食べたし、ご飯食べた天才お風呂も入ったしふはは！", file: "voice/ohuromotabetasi.wav" },
    { name: "起きろー！", file: "voice/okiro.wav" },
    { name: "女の子ですかもしかして", file: "voice/onnnanokodesukamosikasite.wav" },
    { name: "お茶ありがちょんまげ", file: "voice/otyaarigatyonmage.wav" },
    { name: "おちゅかれさま～", file: "voice/otyukaresama.wav" },
    { name: "おちゅかれさまでした～", file: "voice/otyukaresamadesita.wav" },
    { name: "ﾋﾟｶﾁｭｳ", file: "voice/pikatyuu.wav" },
    { name: "ﾋﾟｶﾁｭｳ？", file: "voice/pikatyuu2.wav" },
    { name: "ﾋﾟｰｶｰﾁｭｳ", file: "voice/pikatyuu3.wav" },
    { name: "ﾋﾟｯｶｯﾁｭｳ", file: "voice/pikatyuu4.wav" },
    { name: "ﾋﾟｶｯ……ﾁｭｳ", file: "voice/pikatyuu5.wav" },
    { name: "ぴょこっ", file: "voice/pyoko.wav" },
    { name: "あいつロリコンだから気をつけてね", file: "voice/rorikondakarakiwotuketene.wav" },
    { name: "辛辣で草ｯｱｯｱｯｱｯｱｯｱｗｗ", file: "voice/sinratudekusa.wav" },
    { name: "助かるラスカル", file: "voice/tasukarurassukaru.wav" },
    { name: "助かるよー", file: "voice/tasukaruyo.wav" },
    { name: "てててててててててて", file: "voice/tetetetete.wav" },
    { name: "ちょちょちょちょちょちょちょちょ", file: "voice/tyotoyotyotyotyotyo.wav" },
    { name: "忘れてた☆", file: "voice/wasuretetahosi.wav" },
    { name: "私はいつか好きピにメイド服を着せてオムライスを作ってもらいたい", file: "voice/watasihaituka.wav" },
    { name: "やばい！やばい！", file: "voice/yabaiyabai.wav" },
    { name: "やめてくれ！", file: "voice/yametekure.wav" },
    { name: "やめてよ～", file: "voice/yameteyo.wav" },
    { name: "ﾊｧ～～～やられたーやられたーやられたよー", file: "voice/yararetayararetayararetayo.wav" },
    { name: "ﾖｲﾁｮ……ﾖｲﾁｮ……ﾑ､ﾑﾘ", file: "voice/yoityoyoityomumuri.wav" },
    { name: "ざぁこざぁこ", file: "voice/zalakozalako.wav" },
    { name: "全然酔ってない", file: "voice/zenzenyottenai.wav" },
    { name: "ありがとう↑", file: "voice2/arigatou.wav" },
    { name: "電話掛けても声かけても起きません", file: "voice2/denwakaketemokoekaketemo.wav" },
    { name: "ファイトだよ", file: "voice2/faitodayo.wav" },
    { name: "配信赤字一分前で寝た", file: "voice2/haisinakajiippunnmae.wav" },
    { name: "私は一回寝たら起きないから", file: "voice2/ikkainetaraokinai.wav" },
    { name: "この私が起きるわけないさ", file: "voice2/konowatasigaokiruwakenaisa.wav" },
    { name: "またずっと寝てた", file: "voice2/matazuttoneteta.wav" },
    { name: "眠いです今日めっちゃ", file: "voice2/nemuidesu.wav" },
    { name: "おはよう", file: "voice2/ohayou.wav" },
    { name: "私いつも静かに寝る定評の私なんだけど", file: "voice2/sizukanineruteihyou.wav" },
    { name: "そだよ", file: "voice2/sodayo.wav" },
    { name: "添い寝配信助かるよ", file: "voice2/soinehaisin.wav" },
    { name: "そんなの嘘だ", file: "voice2/sonnnanousoda.wav" },
    { name: "助かられた", file: "voice2/tasukarareta.wav" },
    { name: "ウケる", file: "voice2/ukeru.wav" },
    { name: "私ってマジで静かに寝るよね", file: "voice2/watashittemajide.wav" },
    { name: "やばいです", file: "voice2/yabaodesu.wav" },
    { name: "そうヤクキメ配信して寝ました", file: "voice2/yakukimehaisin.wav" },
    { name: "あー無理ー", file: "voice3/abunee.wav" },
    { name: "別に他に推しができること自体は私は別に何も思わない", file: "voice3/betunihokaniosigadekirukoto.wav" },
    { name: "ボタンボイスにされるよ", file: "voice3/botanvoicenisareruyo.wav" },
    { name: "えー駄目だよ", file: "voice3/damedayo7.wav" },
    { name: "えーもう", file: "voice3/eemouinakunaruno.wav" },
    { name: "はぴはぴ", file: "voice3/hapihapi.wav" },
    { name: "はぴはぴイェイ", file: "voice3/hapihapiyei.wav" },
    { name: "人と仲良くなるには常に謙虚な姿勢が大事なんだぞ", file: "voice3/hitotonakayokunaruniha.wav" },
    { name: "チーにゃ！", file: "voice3/jantama1.wav" },
    { name: "ポンにゃ！", file: "voice3/jantama2.wav" },
    { name: "雀魂やらねぇぞ私は", file: "voice3/jantama3.wav" },
    { name: "JKっていいな", file: "voice3/jktteiina.wav" },
    { name: "感謝", file: "voice3/kansha.wav" },
    { name: "キレそう", file: "voice3/kiresou.wav" },
    { name: "ｷｽｼﾀｲ", file: "voice3/kisusitai.wav" },
    { name: "🌳🍣🌞", file: "voice3/kisusitaiyou.wav" },
    { name: "ねこ", file: "voice3/neko.wav" },
    { name: "寝ろ", file: "voice3/nero.wav" },
    { name: "寝てもええんやで", file: "voice3/netemoeenyade.wav" },
    { name: "んどういうこと？", file: "voice3/nndoyukoto.wav" },
    { name: "ﾊﾟﾝｯ", file: "voice3/pan.wav" },
    { name: "ぽよぽよ", file: "voice3/poypoyo.wav" },
    { name: "理解した瞬間恥ずかしくなった", file: "voice3/rikaisitashunkanhazukasikunatta.wav" },
    { name: "最悪やね", file: "voice3/saiakuyane.wav" },
    { name: "そんなわけあるか", file: "voice3/sonnnawakearuka.wav" },
    { name: "私の気が狂わない限り顔出しなんかしない", file: "voice3/watasinokigakuruwanaikagiri.wav" },
    { name: "ガチしょうもない", file: "voice4/gatichoumonai.wav" },
    { name: "はわわわわ……んっ", file: "voice4/hawawawawa.wav" },
    { name: "無理に決まっとんじゃ", file: "voice4/murinikimattonja.wav" },
    { name: "なに？", file: "voice4/nani.wav" },
    { name: "助からないで", file: "voice4/tasukaranaide.wav" },
    { name: "たすかるーらすかるーまらかすー", file: "voice4/tasukarurasuskarumarakasu.wav" },
    { name: "てへてへ", file: "voice4/tehetehe.wav" },
    { name: "オタクくんざーこざーこｗざーこざーこ", file: "voice5/otakukunzakozako.wav" },
    { name: "助かるラスカルヘクトパスカルってな", file: "voice5/tasukarurasukaruhekutopasukaru.wav" },
    { name: "ﾄﾞｩｰﾝ↑", file: "voice6/doluun.wav" },
    { name: "はわわわわ……ハッハッハ！", file: "voice6/hawaaaa.wav" },
    { name: "ヘンタイ", file: "voice6/hentai.wav" },
    { name: "ぽえぽえぽえ", file: "voice6/poepoe.wav" },
    { name: "ひっひっふー", file: "voice7/hihhihhu.wav" },
    { name: "ふにゅ～！いつもありがとうなのら～", file: "voice7/hunyuitsumoarigatounanora.wav" },
    { name: "ﾅﾝ~ﾅﾝ~ﾅﾝ~……", file: "voice7/nannannan.wav" },
    { name: "乙じゃないッスまだ", file: "voice7/otsujanaissumada.wav" },
    { name: "きも（小声）", file: "voice7/kimo.wav" },
    { name: "にこ（ねっとり）", file: "voice7/nikonettori.wav" }
];

const grid = document.getElementById('button-grid');

// 配列をループ回してボタンを作る
voiceList.forEach((voice, index) => {
    const btn = document.createElement('button');
    btn.textContent = voice.name;
    btn.className = 'voice-button';
    
    // クリック時の処理
    btn.onclick = () => {
        const audio = new Audio(voice.file);
        audio.play();
    };
    
    grid.appendChild(btn);
});